package com.akashk.palette.ui.theme
import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF6750a4)
val light_onPrimary = Color(0xFFffffff)
val light_primaryContainer = Color(0xFFeaddff)
val light_onPrimaryContainer = Color(0xFF22005d)
val light_secondary = Color(0xFF625b71)
val light_onSecondary = Color(0xFFffffff)
val light_secondaryContainer = Color(0xFFe8def8)
val light_onSecondaryContainer = Color(0xFF1e192b)
val light_tertiary = Color(0xFF7d5260)
val light_onTertiary = Color(0xFFffffff)
val light_tertiaryContainer = Color(0xFFffd8e4)
val light_onTertiaryContainer = Color(0xFF31101d)
val light_error = Color(0xFFba1b1b)
val light_errorContainer = Color(0xFFffdad4)
val light_onError = Color(0xFFffffff)
val light_onErrorContainer = Color(0xFF410001)
val light_background = Color(0xFFfffbfe)
val light_onBackground = Color(0xFF1c1b1e)
val light_surface = Color(0xFFfffbfe)
val light_onSurface = Color(0xFF1c1b1e)
val light_surfaceVariant = Color(0xFFe7e0ec)
val light_onSurfaceVariant = Color(0xFF49454f)
val light_outline = Color(0xFF79757f)
val light_inverseOnSurface = Color(0xFFf4eff4)
val light_inverseSurface = Color(0xFF313033)

val dark_primary = Color(0xFFd0bcff)
val dark_onPrimary = Color(0xFF381e73)
val dark_primaryContainer = Color(0xFF4f378b)
val dark_onPrimaryContainer = Color(0xFFeaddff)
val dark_secondary = Color(0xFFcbc2db)
val dark_onSecondary = Color(0xFF332d41)
val dark_secondaryContainer = Color(0xFF4a4458)
val dark_onSecondaryContainer = Color(0xFFe8def8)
val dark_tertiary = Color(0xFFefb8c8)
val dark_onTertiary = Color(0xFF4a2532)
val dark_tertiaryContainer = Color(0xFF633b48)
val dark_onTertiaryContainer = Color(0xFFffd8e4)
val dark_error = Color(0xFFffb4a9)
val dark_errorContainer = Color(0xFF930006)
val dark_onError = Color(0xFF680003)
val dark_onErrorContainer = Color(0xFFffdad4)
val dark_background = Color(0xFF1c1b1e)
val dark_onBackground = Color(0xFFe6e1e5)
val dark_surface = Color(0xFF1c1b1e)
val dark_onSurface = Color(0xFFe6e1e5)
val dark_surfaceVariant = Color(0xFF49454f)
val dark_onSurfaceVariant = Color(0xFFcac4cf)
val dark_outline = Color(0xFF948f99)
val dark_inverseOnSurface = Color(0xFF1c1b1e)
val dark_inverseSurface = Color(0xFFe6e1e5)

val seed = Color(0xFF6750a4)
val error = Color(0xFFba1b1b)
